[google]
type = "service_account"
project_id = "jovial-monument-454000-a4"
private_key_id = "790fe508a1c55dd9708692a9b576fc72e9931945"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDkX7mahyTMaR4X
4OJ6/TrwxrqXdXQOa58e2Qmq2ja+yB/aHPdQxaBicqDrp90kMrHNdfTAozZkrdSE
cgEhGFkwQMixUhnRWwmE/XzFg565Cdn2dT1GIzJ2zM7p9UgVdsDP5+NM7Zx8ZJbH
Fes7v64hKS/40XWpZRSVdSaAisUuKuho/quP4m1/vATNFvFoRVdZmyvxdpJ7lWg1
cZvyOptHJP7SgULygoDcxYA+prkbqov+eIP2IVfCi7jelwAjFbtU5xsPYy8dcVvj
L52OTutmmDcQH+MN0dznfRRe8l2LAW3q3/ml5cQ5IBlzShA/x81bfEjw32OkhXji
hxOO6fF/AgMBAAECggEAXbJ6m5B0BBviuWhOc6h+7LeUabzKQ3pbXBQvF7aU/Hxu
ORZmT/DtZ0bhiB4kqIvWEFajdv/furnpNffyR6pOOXJzBPGK3y7rPnGkJgNk9UU5
9JjQbXzWYRCRmkLE8u14mTRqOS9J421/wSnYi/iOUFOuN3d0v23V3qYkiFunH9O7
UPyRZ8bGnExZN7hlEOpcpvrnOH0Xs+ReCbzACc12CW3tJ0Don/lgjM0mZDkmrX1H
SdjjNDTlw9yYL7CDhlwvPX9l7VpGHzN/xeM8O9t1xVbyiZYNiOhyRmk4BcOxOJdM
pH9XyhaeeCB/P8twIOVNL7UJ7S8RNX9OUQPLf+PVVQKBgQD80lG7qkVuxyA1zTvn
FSuO0wcLwZjceJGGc8G5uHoQux+4SwavKj4so28FjEREp60aeIYcX9Z/x/IsVbYG
-----END PRIVATE KEY-----"""
client_email = "vending-machine-bot@jovial-monument-454000-a4.iam.gserviceaccount.com"
client_id = "105533472426029574233"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/vending-machine-bot%40jovial-monument-454000-a4.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
